version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres_atividade
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: Escola
    ports:
      - "5432:5432"
    volumes:
      - ./ScriptSQL/:/ScriptSQL/
    
